### ISSUE TITLE
Are you looking for a code review?

### ISSUE THREAD

**Issue by MarkBennett** [CAYdenberg/hypocube#79]
I'm tied up for the next few days, but could squeeze one in next week if you'd like.

**Comment by CAYdenberg** [comment]
Thanks for all your feedback. 

I'm not too concerned about the internals at this point, I mostly want to know if the docs are sensible enough that someone else could get started with it. If it turns out to be generally useful enough that it needs to be expanded/maintained over the long term, then hopefully someone else can read the code too :)
